name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        # os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: install
        run: |
          yarn install
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: |
          yarn build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

