name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

  strategy:
    fail-fast: false
    matrix:
      os: [windows-latest, macos-latest, ubuntu-latest]

  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: "16"

    - name: Install Dependencies
      run: npm install

    - name: Build Electron App
      run: npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
